### ISSUE TITLE
BBC Sounds on Logitech Squeezebox Radio

### ISSUE THREAD

**Issue by Dickie47** [expectingtofly/LMS_Radio_Favourites_Plugin#8]
Many thanks for creating the BBC Sounds plug-in for LMS, enabling me to listen to radio on the Squeezebox.
However, as I'm a novice and spent awhile getting to this point, I seem only to be able to play BBC Sounds if my Apple iMac is on, using the Music Library to connect to it. Can you guide me to an idiot proof work round, if there is one, to enable me to play the radio without the iMac?
Thanks, Dickie47

**Comment by expectingtofly** [comment]
You are correct, the BBC sounds plugin is a plugin for Logitech Media Server which you need to have running and connected to from your Radio to work.  Most people buy a very low powered Raspberry PI or similar and install PiCoreplayer on it. That includes LMS and can run 24/7.  https://www.picoreplayer.org/landingzone_option2.html

It is really straight forward to set up and once done just sits there running.   People on the forums will be more than happy to help you get that working if you decide to go that route. For example here's a recent discussion : https://forums.slimdevices.com/forum/user-forums/logitech-media-server/1633722-a-guide-for-installing-pcp-from-scratch

**Comment by Dickie47** [comment]
Many thanks for the clarification. I wondered what the references to the RaspberryPl was in the forums, so thanks for that,
good to know, I’ll look into it, many many thanks.
Dickie47
